version: "3.9"

services:
  app:
    build: .
    container_name: ML_Dermarlet
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always